<?php if($this->user) {
		echo $this->user;
	?>	
<?php }else{?>
	<div id="auth">
		<a id="registration-link">Регистрация</a>
		<p id="registrated-already">Я уже зарегистрирован:</p>
		<input class="auth-input" id="auth-login" name="auth-login" type="text" placeholder="Логин"></input>
		<input class="auth-input" id="auth-password" name="auth-password" type="password" placeholder="Пароль"></input>
		<a class="auth-action" id="auth-forgot-pass">Забыли пароль?</a>
		<a class="auth-action" id="auth-enter">Войти</a>
		<!--<a id="enter-link">Вход</a>
		/ 
		<a id="registration-link">Регистрация</a>-->
	</div>
<?php }?>