	<div id="service_items">
		<ul>
			
			<?php
				if (isset($this->data['articles'])) { 
					foreach($this->data['articles'] as $key => $article) { 		
			?>
			<li class="service_item">
				<div id="service_logo_div1" class="service_logo_div">
					<a href="<?php echo URL . 'services/view/'.  $article['slug'] ; ?>" id="service_logo1" class="service_logo"> </a>
				</div>
				<div class="service_preview">
					<a class="service_preview_title" href="<?php echo URL . 'services/view/'.  $article['slug'] ; ?>"><?php echo $article['title']; ?></a>
					<p class="service_preview_text"><?php echo substr(strip_tags($article['content']), 0, 200); ?> </p>
					<a href="<?php echo URL . 'services/view/'.  $article['slug'] ; ?>" class="more_link"><span>подробнее</span></a>
				</div>
			</li>
			<?php
					}
				}
			?>
		</ul>
	</div>