<p id="room-caption">Личный кабинет</p>
<p id="room-objects-pages">Текущие страницы объектов:</p>
<div id="object-page-link">
	<a href="#">Название объекта</a>
</div>
<p id="room-create-caption">
	Создание страницы объекта недвижимости
</p>
<p class="room-field-caption">Месторасположение</p>
<select id="select-location" class="room-field-file"></select>
<hr>
<p class="room-field-caption">Фотографии</p>
<input type="file" id="room-file-photo" name="room-file-photo" class="room-field-file">
<br>
<span class="file-upload-info">Формат: .jpg, .png не более 1Мб</span>
<hr>
<p class="room-field-caption">Видео</p>
<input type="file" id="room-file-video" name="room-file-video" class="room-field-file">
<br>
<span class="file-upload-info">Формат: .avi, .mpeg не более 10Мб</span>
<hr>
<p class="room-field-caption">Описание объекта</p>
<hr>
<p class="room-field-sub-caption">Общая площадь</p>
<input type="text" id="room-object-square" name="room-object-square" class="room-field">
<hr>
<p class="room-field-sub-caption">Кол-во этажей</p>
<input type="text" id="room-object-floors" name="room-object-floors" class="room-field">
<hr>
<p class="room-field-sub-caption">Класс</p>
<select id="room-select-class" class="room-field-file"></select>
<hr>
<p class="room-field-caption">Год постройки</p>
<select id="room-object-year" class="room-field-file"></select>
<hr>
<p class="room-field-caption">Удаленность от метро</p>
<input type="text" id="room-from-metro" name="room-from-metro" class="room-field">
<hr>
<p class="room-field-caption">Текущие арендаторы</p>
<input type="text" id="room-arendators" name="room-arendators" class="room-field">
<hr>
<p class="room-field-caption">Дополнительные услуги</p>
<hr>
<p class="room-field-sub-caption">Кафе</p>
<input type="checkbox" id="room-service-cafe" name="room-service-cafe" class="room-field">
<hr>
<p class="room-field-sub-caption">Салон красоты</p>
<input type="checkbox" id="room-service-salon" name="room-service-salon" class="room-field">
<hr>
<p class="room-field-sub-caption">Фитнес центр</p>
<input type="checkbox" id="room-service-fitnes" name="room-service-fitnes" class="room-field">
<hr>
<p class="room-field-sub-caption">Другое</p>
<input type="text" id="room-service-other" name="room-service-other" class="room-field">
<hr>
<p class="room-field-caption">Свободные помещения</p>
<hr>
<p class="room-field-sub-caption">Этаж</p>
<input type="text" id="room-object-floor" name="room-object-floor" class="room-field">
<hr>
<p class="room-field-sub-caption">Площадь</p>
<input type="text" id="room-free-object-area" name="room-free-object-area" class="room-field">
<hr>
<p class="room-field-sub-caption">Возможная дата заезда</p>
<input type="text" id="room-free-object-date" name="room-free-object-date" class="room-field">
<hr>
<p class="room-field-sub-caption">Отделка</p>
<input type="text" id="room-free-object-wall" name="room-free-object-wall" class="room-field">
<hr>
<p class="room-field-sub-caption">Планировка</p>
<input type="file" id="room-file-planing" name="room-file-planing" class="room-field-file">
<br>
<span class="file-upload-info">Формат: .jpg, .png не более 1Мб</span>
<hr>
<p class="room-field-sub-caption">Стоимость (без НДС)</p>
<input type="text" id="room-free-object-price" name="room-free-object-price" class="room-field">
<hr>
<p class="room-field-sub-caption">Отсутствуют</p>
<input type="checkbox" id="room-no-object" name="room-no-object" class="room-field">
<hr>
<div id="add-room"></div>