<div id="auth">
	<p id="logined-caption">
		Здравствуйте, <span id="not-active-user"><?php echo $this->username;// ?></span>
	</p>
	<p class="not-active-title">Ваш аккаунт не активирован. Если после регистрации вы не получили письмо активации, укажите свой email адрес и нажмите OK.</p>
	<input id="not-active-email" name="not-active-email" type="text" placeholder="Email">
	<br><span class="reg-error"></span>
	<hr style="margin:0; border-width:0px;">
	<p id="not-active-submit-mess">Письмо отправлено.</p>
	<div id="not-active-submit"></div>
	<div id="logined-logout"></div>
</div>