<div class="section">
		<div id="admin_edit">
			<img src="<?php echo URL . "images/admin_new_zap_h1.png"?>">
			<h1>Добавление новой записи</h1>
			<form method="get" action="<?php echo URL . "admin/addarticle"?>">
				<div id="admin_edit_left">
					<p>Заголовок<span id="red_star">*</span></p>
					<input type="text" id="admin_edit_name" name="h1">
					<p>Слаг<span id="red_star">*</span></p>
					<input type="text" id="admin_edit_name" name="name">
					<p>Рубрика<span id="red_star">*</span></p>
					<select size="1" name="rubric">
						<?php print_r($this->page) ?>
					</select>
					<p>Публикация</p>
					<select size="1" name="public">
						<option value="1">Публиковать</option>
						<option value="0">Не публиковать</option>
					</select>
					<!-- <p>Язык</p>
					<select size="1" name="admin_edit_lang">
						<option value="0"></option>
					</select> -->
					<p>Текст</p>
					<script type="text/javascript" src="http://js.nicedit.com/nicEdit-latest.js"></script> <script type="text/javascript">
							bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
   						</script>
  						<textarea class="article" name="content" placeholder="Здесь могла бы быть Ваша РЕКЛАМА..."></textarea>
					</div>
				<div id="admin_edit_right">
					<div id="admin_edit_right_first">
						<div class="admin_edit_head">
							Опубликовать
						</div>
						<input type="image" id="admin_edit_save_draft"  src="<?php echo URL . "images/admin_edit_save_draft.png"?>">
						<input type="image" id="admin_edit_preview"  src="<?php echo URL . "images/admin_edit_preview.png"?>">
						<p>Статус: <b id="status">черновик</b> <a href="">Редактировать</a></p>
						<p id="admin_edit_right_first_center">Видимость: <b id="status">публичная</b> <a ref="">Редактировать</a></p>
						<p><a href=""><img src="<?php echo URL . "images/admin_edit_calendar.png"?>"></a>Видимость: <b id="status">публичная</b> <a href="">Редактировать</a></p>
						<div id="admin_edit_footer">
							<input type="image" id="admin_edit_publish"  src="<?php echo URL . "images/admin_edit_publish.png"?>">
						</div>
					</div>
					<div id="admin_edit_right_second">
						<div class="admin_edit_head">
							Метки
						</div>
						<input type="text" id="admin_edit_metha" name="keywords" value="Добавить новую метку">
						<input type="image" id="admin_edit_add"  src="<?php echo URL . "images/admin_edit_add.png"?>">
						<p>Если меток несколько, разделите их запятыми</p>
						<a href="">Выберите наиболее популярные метки</a>
					</div>
				</div>
				<input type="submit" value="Сохранить">
			</form>
		</div>
	</div>