	<div class="section">
		<div id="admin_biblio">
			<img src="<?php echo URL . 'images/admin_del_zap_h1.png'?>">
			<h1>Удаление записи</h1>
			<form action="">
				<h2>Все записи</h2>
				<select size="1" name="admin_biblio_time">
					<option value="0">За все время</option>
				</select>
				<select size="1" name="admin_biblio_page">
					<option value="0">На всех страницах</option>
				</select>
				<select size="1" name="admin_biblio_page">
					<option value="0">Во всех разделах</option>
				</select>
				<table  border="1" cellspacing="0" bordercolor="#dfdfdf" rules="rows">
					<thead>
  						<tr>
   							<td class="admin_biblio_checkbox"><input type="checkbox" name="all"></td>
   							<td class="admin_biblio_recordname">Запись</td>
   							<td class="admin_biblio_author">Автор</td>
   							<td class="admin_biblio_pages">Страницы</td>
   							<td class="admin_biblio_metha">Метки</td>
   							<td class="admin_biblio_mess"><img src="<?php echo URL . 'images/admin_table_head_mess.png'?>"></td>
   							<td class="admin_biblio_date">Дата</td>
  						</tr>
 					</thead>
 					<tbody>
 						<tr valign="top">
   							<td class="admin_biblio_checkbox"><input type="checkbox" name="1"></td>
   							<td class="admin_biblio_recordname"><a>(без заголовка)</a> - черновик</td>
   							<td class="admin_biblio_author">admin</td>
   							<td class="admin_biblio_pages">Новости</td>
   							<td class="admin_biblio_metha">Метки отсутствуют</td>
   							<td class="admin_biblio_mess"><img src="<?php echo URL . 'images/admin_no_mess.png'?>"></td>
   							<td class="admin_biblio_date"><p>09.08.2012<br />Последнее изменение</p></td>
  						</tr>
  						<tr valign="top">
   							<td class="admin_biblio_checkbox"><input type="checkbox" name="2"></td>
   							<td class="admin_biblio_recordname">Привет, мир!</td>
   							<td class="admin_biblio_author">admin</td>
   							<td class="admin_biblio_pages"><a>Новости</a></td>
   							<td class="admin_biblio_metha">Метки отсутствуют</td>
   							<td class="admin_biblio_mess"><p id="admin_biblio_mess_p">1</p></td>
   							<td class="admin_biblio_date"><p>05.05.2010<br />Опубликована</p></td>
  						</tr> 					
  					</tbody>
					<tfoot>
						<tr>
   							<td class="admin_biblio_checkbox"><input type="checkbox" name="all"></td>
   							<td class="admin_biblio_filename">Запись</td>
   							<td class="admin_biblio_author">Автор</td>
   							<td class="admin_biblio_pages">Страницы</td>
   							<td class="admin_biblio_metha">Метки</td>
   							<td class="admin_biblio_mess"><img src="<?php echo URL . 'images/admin_table_head_mess.png'?>"></td>
   							<td class="admin_biblio_date">Дата</td>
  						</tr>
  					</tfoot>
				</table>
				<input type="image" id="admin_del_zap_submit"  src="<?php echo URL . 'images/admin_del_zap_submit.png'?>">
			</form>
		</div>
	</div>