	<div class="section">
		<div id="admin_edit">
			<img src="images/admin_red_zap_h1.png">
			<h1>Редактирование записи</h1>
			<form action="">
				<div id="admin_edit_left">
					<p>Заголовок<span id="red_star">*</span></p>
					<input type="text" id="admin_edit_name">
					<p>Страница<span id="red_star">*</span></p>
					<select size="1" name="admin_edit_page">
						<option value="0"></option>
					</select>
					<p>Разрешение редактирования</p>
					<select size="1" name="admin_edit_permission">
						<option value="0"></option>
					</select>
					<p>Язык</p>
					<select size="1" name="admin_edit_lang">
						<option value="0"></option>
					</select>
					<p>Текст</p>
					<img src="images/editor.png">
				</div>
				<div id="admin_edit_right">
					<div id="admin_edit_right_first">
						<div class="admin_edit_head">
							Опубликовать
						</div>
						<input type="image" id="admin_edit_save_draft"  src="images/admin_edit_save_draft.png">
						<input type="image" id="admin_edit_preview"  src="images/admin_edit_preview.png">
						<p>Статус: <b id="status">черновик</b> <a href="">Редактировать</a></p>
						<p id="admin_edit_right_first_center">Видимость: <b id="status">публичная</b> <a ref="">Редактировать</a></p>
						<p><a href=""><img src="images/admin_edit_calendar.png"></a>Видимость: <b id="status">публичная</b> <a href="">Редактировать</a></p>
						<div id="admin_edit_footer">
							<input type="image" id="admin_edit_publish"  src="images/admin_edit_publish.png">
						</div>
					</div>
					<div id="admin_edit_right_second">
						<div class="admin_edit_head">
							Метки
						</div>
						<input type="text" id="admin_edit_metha" value="Добавить новую метку">
						<input type="image" id="admin_edit_add"  src="images/admin_edit_add.png">
						<p>Если меток несколько, разделите их запятыми</p>
						<a href="">Выберите наиболее популярные метки</a>
					</div>
				</div>
				
			</form>
		</div>
	</div>