<script language="JavaScript">
	function changepass() {	
		if ($("#admin-profile-new-pass").is(":checked")){
				$("#admin-div-profile-rep-pass").show();
				$("#admin-profile-rep-pass").attr("required", "0");
		  	} else {
				$("#admin-div-profile-rep-pass").hide();
				$("#admin-profile-rep-pass").removeAttr('required');	
		 	}
	}
</script>	
	<div class="section">
		<div id="admin-profile">
			<img src="<?php echo URL . "images/admin_profile_h1.png"?>">
			<h1>Параметры профиля</h1>
			<?php // print_r($this->page);?>
			<form action="<?php echo URL . "admin/profile"?>" name="admin_change_profile">
				<div>
					<p>Имя<span id="red-star">*</span></p>
					<input required name="profile-name" type="text" id="admin-profile-name" value="<?php echo $this->page['username']?>">
				</div>
				<div>
				<p>Логин<span id="red-star">*</span></p>
				<input required name="profile-login" type="text" id="admin-profile-login" value="<?php echo $this->page['email']?>">
				</div>
				<div>
				<p>Пароль</p>
				<input required name="profile-pass" type="password" id="admin-profile-pass" value="">
				<input id="admin-profile-new-pass" type="checkbox" name="new-password" onchange='changepass()'>Новый пароль</p>
				</div>
				<div id="admin-div-profile-rep-pass">
				<p>Повтор пароля</p>
				<input name="profile-rep-pass" type="password" id="admin-profile-rep-pass">
				</div>
				<div>
				<p>Дата регистрации</p>
				<p class="admin-profile-info"><?php echo $this->page['timestamp']?></p>
				</div>
				<!--<div>
				<p>Дата последнего входа</p>
				<p class="admin_profile_info">2012-08-09 09:22:45</p>
				</div>-->
				<div>
				<p>ID</p>
				<p class="admin-profile-info"><?php echo $this->page['id']?></p>
				</div>
				<input type="image" id="admin-profile-submit"  src="<?php echo URL . "images/admin_profile_submit.png"?>">
			</form>
		</div>
	</div>
