<script language="JavaScript">
	function changepass() {	
		if ($("#admin-profile-new-pass").is(":checked")){
				$("#admin-div-profile-rep-pass").show();
				$("#admin-profile-rep-pass").attr("required", "0");
		  	} else {
				$("#admin-div-profile-rep-pass").hide();
				$("#admin-profile-rep-pass").removeAttr('required');	
		 	}
	}
</script>	
<?php 
	$user = $this->user[0];
?>
<div class="section">
	<div class="admin-block">
		<ul class="list-wrapper">
			<li>
				<img src="<?php echo URL . "images/admin_profile_h1.png"?>" class="mini-image">
			</li>
			<li>
				<h1>Параметры профиля</h1>
			</li>
		</ul>
		<form action="<?php echo URL . "admin/profile"?>" name="admin_change_profile" class="admin-block info-list">
			<p>
				Имя
				<span class="red-star">*</span>
				<input required name="profile-name" type="text" id="admin-profile-name" value="<?php echo $user['name']?>">
			</p>
			<p>
				E-mail
				<span class="red-star">*</span>
				<input required name="profile-login" type="text" id="admin-profile-login" value="<?php echo $user['email']?>">
			</p>
			<ul class="list-wrapper">
				<li>
					<p>
						Пароль
						<input required name="profile-pass" type="password" id="admin-profile-pass" value="">
					</p>
				</li>
				<li>
					<p>
						<input id="admin-profile-new-pass" type="checkbox" name="new-password" onchange='changepass();'>
						Новый пароль
					</p>
				</li>
			</ul>
			<div id="admin-div-profile-rep-pass">
				<p>
					Повтор пароля
					<input name="profile-rep-pass" type="password" id="admin-profile-rep-pass">
				</p>
			</div>
			<p>
				ID
				<span class="id"><?php echo $user['id']?></span>
			</p>
			<input name="profile-id" type="hidden" id="admin-profile-id" value="<?php echo $user['id']?>">
			<input type="image" id="admin-profile-submit"  src="<?php echo URL . "images/admin_profile_submit.png"?>">
		</form>
	</div>
</div>