<div class="section">
		<div id="admin-biblio">
			<img src="<?php echo URL . 'images/admin_red_zap_h1.png'?>">
			<h1>Редактирование записи</h1><br />
			<a href="<?php echo URL . 'portfolio/create'?>"><img src="<?php echo URL . 'images/admin_red_zap_submit.png'?>" style="float:both; margin-left: 15px;"></a><br>
			<form action="">
				<h2>Все записи</h2>
				<select size="1" name="admin-biblio-time">
					<option value="0">За все время</option>
				</select>
				<select size="1" name="admin-biblio-page">
					<option value="0">На всех страницах</option>
				</select>
				<select size="1" name="admin-biblio-page">
					<option value="0">Во всех разделах</option>
				</select>
				<table  border="1" cellspacing="0" bordercolor="#dfdfdf" rules="rows">
					<thead>
  						<tr>
   							<td class="admin-biblio-recordname">Страница</td>
   							<td class="admin-biblio-pages">Линк</td>
   							<td class="admin-biblio-action">Действия</td>
  						</tr>
 					</thead>
 					<tbody>
 						<?php foreach ($this->read as $key => $seo) { ?>
 							<tr valign="top">
								<td class="admin-biblio-recordname"><a href=""><?php echo $seo['title'];?></a></td>
								<td class="admin-biblio-pages"><a href="<?php echo URL .  $seo['title'];?>"><?php echo URL . $seo['title'];?></a></td>
								<td class="admin-biblio-action">
									<a href="<?php echo URL . "seo/read/{$seo['id']}"?>" title="Редактировать"><img src="<?php echo URL . 'images/action_edit.png'?>" class="action-edit"></a>
								</td>
							</tr>		
 						<?php } ?>		
  					</tbody>
					<tfoot>
						<tr>
   							<td class="admin-biblio-filename">Страница</td>
   							<td class="admin-biblio-pages">Линк</td>
   							<td class="admin-biblio-action">Действия</td>
  						</tr>
  					</tfoot>
				</table> 
			</form>
		</div>
	</div>
