<p style="
			margin:0;
			color:#757575;
			font: italic 18px Verdana, Arial, Helvetica, Tahoma, sans-serif;">
	На Ваш email подан запрос смены пароля на сайте 
	<a 
		style="
			color:#40b0e0;
			text-decoration:none;
			" 
		href="
			<?php echo URL;?>
		">
	<?php $var = parse_url(URL); echo $var['host'];?></a>.
</p>
<p style="
			color:#757575;
			font: 14px Verdana, Arial, Helvetica, Tahoma, sans-serif;
			margin:0;
			margin-top:10px;
			margin-bottom:5px;
			">
	Если Вы хотите сменить пароль, пройдите по ссылке:
</p>
<a style="	
			text-decoration:none;			
			color:#40b0e0;
			font:italic 14px Verdana, Arial, Helvetica, Tahoma, sans-serif;"
	href="<?php echo URL.'auth/passconfirm/id/'.$this->id.'/code/'.$this->code; ?>">
	<?php echo URL.'auth/passconfirm/id/'.$this->id.'/code/'.$this->code; ?>
</a>