<div id="mail" style="text-align:center; background-color:#f2f0ed;">
	<div id="header-mail" style="background-color:#747474;">
		<a href="<?php echo URL; ?>" id="mail-logo" style="text-decoration:none;margin:0 auto;display:block;color:#EEE;text-align:left;width:180px;padding:10px;">
			<p id="mail-logo-title" style="margin:0;font:italic 18px/17px Arial, Helvetica, Tahoma, sans-serif;letter-spacing:1px;">Nedvizhimost.com</p>
			<p id="mail-logo-desc" style="margin:0;font: bold italic 10px/10px Arial, Helvetica, Tahoma, sans-serif;">краткое описание деятельности</p>
		</a>
	</div>
	<div id="content-mail" style="text-align:center;padding:10px;">
		<?php echo $this->layout()->content; ?>
	</div>
	<div id="footer-mail" style="background-color:#747474;">
		<div id="copyright"  
			style="
				color: #FFFFFF;
    			font: italic 11px Verdana,Arial,Helvetica,Tahoma,sans-serif;
    			padding: 10px;
			">
				Недвижимость © 2012
				<br>
				Все права защищены
		</div>
	</div>
</div>