<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=windows-1251" />
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headScript(); ?>
	</head>
	<body>
		<div id="body-wrapper">
			<div id="header">
				<div id="header-content">
					<a href="#" id="main-logo">
						<p id="main-logo-title">Nedvizhimost.com</p>
						<p id="main-logo-desc">краткое описание деятельности</p>
					</a>
					<div id="main-top-menu">
						<a href="#" class="main-top-menu-item" href="#">Офисные помещения</a>
						<a href="#" class="main-top-menu-item" href="#">Торговые помещения</a>
						<a href="#" class="main-top-menu-item" href="#">Склады</a>
						<a href="#" class="main-top-menu-item" href="#">Новости</a>
					</div>
					<input id="search-input" name="input-search" type="text" placeholder="поиск...">
				</div>
			</div>
			<div id="main">
				<div id="left">
					<div id="main-left-menu">
						<a href="#" class="main-left-menu-item" href="#">Главная</a>
						<a href="#" class="main-left-menu-item" href="#">Собственники</a>
						<a href="#" class="main-left-menu-item" href="#">Аналитика</a>
						<a href="#" class="main-left-menu-item" href="#">Исследования</a>
						<a href="#" class="main-left-menu-item" href="#">Рейтинг риэлторов</a>
						<a href="#" class="main-left-menu-item" href="#">Производственные комплексы</a>
						<a href="#" class="main-left-menu-item" href="#">Другие помещения</a>
						<a href="#" class="main-left-menu-item" href="#">Запросы на помещения</a>						
					</div>
					<a href="#" id="events">Мероприятия</a>
					<ul id="best-realty-list">
						<li>
							<a href="#">Лучшая недвижимость</a>
							<p>описание новости. При клике на заголовок - откроется полностью</p>
						</li>
						<li>
							<a href="#">Лучшая недвижимость</a>
							<p>описание новости. При клике на заголовок - откроется полностью</p>
						</li>
						<li>
							<a href="#">Лучшая недвижимость</a>
							<p>описание новости. При клике на заголовок - откроется полностью</p>
						</li>
					</ul>
				</div>
				<div id="center-right">
					<div id="center">
						<?php echo $this->layout()->content; ?>
					</div>
					<div id="right">
						<?php 
							if($this->username){
								echo $this->partial('partial/logined.phtml',array(
													    'username' => $this->username));
							}else{
								echo $this->partial('partial/not_logined.phtml');
							}
						?> 
						<a class="banner" href="#"><img src="http://moscow.atplus.com.ua/img/banner.png"></a>
						<a class="banner" href="#"><img src="http://moscow.atplus.com.ua/img/banner.png"></a>
						<div id="context-commercial">
						</div>
					</div>
				</div>
			</div>
			<div id="footer">
				<div id="copyright">
					Недвижимость &copy; 2012<br>
					Все права защищены
				</div>
			</div>
		</div>
		<?php //echo $this->action('register', 'auth'); ?>
		<?php if(!$this->username){
			echo $this->partial('partial/registration.phtml');
		}
		?>      
	</body>
</html>